homepage_settings:
  countdown:
    show: true
    timezone: America/Chicago
    deadline: 2026-07-01 23:59
  modal:
    show: false
    delay: 5000
  testimonials:
    show: true
    title: "Testimonials"
  gallery:
    show: true
    title: "See how the previous ElixirConf US went!"
  tickets: true
