homepage_settings:
  countdown:
    show: false
    timezone: America/New_York
    deadline: 2025-08-28 09:00
  modal:
    show: true
    delay: 5000
  testimonials:
    show: true
    title: "Testimonials"
  gallery:
    show: true
    title: "See how ElixirConf US 2024 went!"
  tickets: true
