---
trainers:
- _participants/Francesco-cesarini.md
- _participants/francisco-castro.md
- _participants/gus-workman.md
- _participants/justin-schneck.md
- _participants/josh-price.md
- _participants/shankar-dhanasekaran.md
- _participants/nittin-shankar.md
- _participants/Vittoria-Bitton.md
- _participants/yuri-oliveira.md
- _participants/zach-daniel.md
